---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: custom-metrics-autoscaler-subscription
  namespace: openshift-devspaces
spec:
  channel: stable
  installPlanApproval: Automatic
  name: openshift-custom-metrics-autoscaler-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: custom-metrics-autoscaler.v2.17.2-2